### ISSUE TITLE
patch for rtl8189es has drifted

### ISSUE THREAD

**Issue by vjeeva** [riptidewave93/npn2-debian#4]
The RTL8189ES patch doesn't apply since it doesn't match the upstream master code anymore.

Looking at the upstream code - seems it has been updated a few times with good fixes: https://github.com/jwrdegoede/rtl8189ES_linux/blob/master/os_dep/linux/ioctl_cfg80211.c.

Might not need the patch at all anymore? I'm still building but FYI @riptidewave93 :)

**Comment by riptidewave93** [comment]
Working on fixing this by rebasing and updating everything, will have a PR ready once the work is done. Looks like rtl8189es doesn't require any patches anymore :)
